name: Cache Firmware

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set cache key
        id: vars
        run: echo "key=fw-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Download firmware
        run: |
          mkdir -p FIRMWARE

          echo "Downloading A34 firmware..."
          wget -O FIRMWARE/A34.tar.zst \
          "https://huggingface.co/buckets/Zears14/lumifiles/resolve/A346E.tar.zst?download=true"

          echo "Downloading A24 firmware..."
          wget -O FIRMWARE/A24.tar.zst \
          "https://huggingface.co/buckets/Zears14/lumifiles/resolve/A245F.tar.zst?download=true"

      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: FIRMWARE
          key: ${{ steps.vars.outputs.key }}