name: Cache Firmware

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'  # every Sunday

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Restore cache (if exists)
        uses: actions/cache@v4
        id: cache-fw
        with:
          path: FIRMWARE
          key: fw-bundle-v3

      - name: Download firmware if missing
        if: steps.cache-fw.outputs.cache-hit != 'true'
        run: |
          mkdir -p FIRMWARE

          echo "Downloading A34 firmware..."
          wget -O FIRMWARE/SM-A346E_OneUi85_firmware.zip \
          "https://h3cked.qzz.io/d/H3CKED_HDD/LumiROM/Base_FW/A346B.zip?sign=nSPfUDaOWHgPp9J_w-sb56skCDdlDC6hZIB7tYekoC0=:0"

          echo "Downloading A24 firmware..."
          wget -O FIRMWARE/SM-A245F_OneUi85_firmware.zip \
          "https://h3cked.qzz.io/d/H3CKED_HDD/LumiROM/Base_FW/A245F.zip?sign=GpyvunbcV76xw7beb90jkAdYrmpaiUPNv_8uSf1LJ5Y=:0"

      - name: Save cache
        if: steps.cache-fw.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: FIRMWARE
          key: fw-bundle-v3
