name: Test

on:
  workflow_dispatch:
    inputs:
      STOCK_DEVICE:
        description: "Put the Model of your phone, remember it starts with SM-"
        required: true
        default: "SM-A325F"
      USE_UI_8_TETHERING_APEX:
        description: "Set True if your kernel BPF version is lower than 5.10"
        required: true
        default: "False"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Setup directories
      run: |
        chmod +x scripts/setup_directories.sh
        chmod +x scripts/zip_creation.sh
        bash scripts/setup_directories.sh FIRMWARE WORK OUT
    
    - name: Set build environment
      shell: bash
      run: |
        echo "STOCK_DEVICE=${{ github.event.inputs.STOCK_DEVICE }}" >> $GITHUB_ENV
        echo "USE_UI_8_TETHERING_APEX=${{ github.event.inputs.USE_UI_8_TETHERING_APEX }}" >> $GITHUB_ENV
        echo "OUTPUT_FILESYSTEM=erofs" >> $GITHUB_ENV
        echo "LUMIROM_VERSION=8.6.1" >> $GITHUB_ENV

        echo "OUT_DIR=$PWD/OUT" >> $GITHUB_ENV
        echo "WORK_DIR=$PWD/WORK" >> $GITHUB_ENV
        echo "FIRM_DIR=$PWD/FIRMWARE" >> $GITHUB_ENV
        echo "DEVICES_DIR=$PWD/LumiROM/Devices" >> $GITHUB_ENV
        echo "APKTOOL=$PWD/bin/apktool/apktool.jar" >> $GITHUB_ENV
        echo "VNDKS_COLLECTION=$PWD/LumiROM/vndks" >> $GITHUB_ENV
        echo "BUILD_PARTITIONS=product,vendor,odm,system_ext,system" >> $GITHUB_ENV

    - name: Check repo
      shell: bash
      env:
        LUMIROM_BUILD: ${{ secrets.LUMIROM_BUILD }}
      run: |
        source scripts/LumiROM.sh
        IS_OFFICIAL

    - name: Test
      env:
        LUMIROM_BUILD: ${{ secrets.LUMIROM_BUILD }}
      run: |
        CURRENT_SIGNATURE=$(printf "%s" "$LUMIROM_BUILD" | sha256sum | cut -d ' ' -f 1)

        echo "$CURRENT_SIGNATURE"

        OFFICIAL_HASH="5c839d21356fbd708985384c0434e474779e57fb4dea8be563fd44311357da1f"

        if [ "$CURRENT_SIGNATURE" == "$OFFICIAL_HASH" ]; then
            export BUILD_STATUS="OFFICIAL"
            export ROM_TAG="✨ LumiROM Official Build"
            
            echo "BUILD_STATUS=OFFICIAL" >> "$GITHUB_ENV"
            echo "ROM_TAG=✨ LumiROM Official Build" >> "$GITHUB_ENV"
        else
            export BUILD_STATUS="UNOFFICIAL"
            export ROM_TAG="🛠️ LumiROM Unofficial Build"
            
            echo "BUILD_STATUS=UNOFFICIAL" >> "$GITHUB_ENV"
            echo "ROM_TAG=🛠️ LumiROM Unofficial Build" >> "$GITHUB_ENV"
        fi

        echo ">> $ROM_TAG detected."
        
    - name: Cleanup
      run: |
        sudo rm -rf *
